services:
  export:
    image: kicad/kicad:10.0
    user: root
    volumes:
      - .:/workspace
    working_dir: /workspace
    entrypoint: ["/bin/bash", "./kiforge.sh"]
    command: [
      "--project-path", "tests/sample_project",
      "--output-dir", "kiforge"
    ]
